In [1]:
import pandas as pd
from sklearn.model_selection import ParameterGrid

import sys
sys.path.append("..")
from src.preprocessing import weigh_norm_densities, align_densities, df_to_densities
from src.utils import cv

In [2]:
# Dados
data_path = "../data/processed/"
returns_path = ''.join([data_path, 'ibovespa_treated.xlsx'])
df = pd.read_excel(returns_path, index_col="time")
df.head()

,2024-12-02,2024-12-03,2024-12-04,2024-12-05,2024-12-06,2024-12-09,2024-12-10,2024-12-11,2024-12-12,2024-12-13,...,2025-11-14,2025-11-17,2025-11-18,2025-11-19,2025-11-21,2025-11-24,2025-11-25,2025-11-26,2025-11-27,2025-11-28
time,,,,,,,,,,,,,,,,,,,,,
10:00:00,0.000011,-0.000372,-0.000035,0.007233,-0.001305,-0.000459,0.002388,0.002212,-0.008001,-0.000824,...,-0.000957,-0.002307,-0.003734,-0.005020,-0.001139,-0.000255,0.002339,0.004176,-0.000224,-0.000238
10:05:00,-0.002271,0.003372,0.001716,0.005538,0.000069,0.006429,0.002343,0.001918,-0.007582,-0.000413,...,-0.001522,0.000739,-0.000613,0.000306,-0.002021,-0.000810,0.001557,-0.001565,-0.000193,0.002906
10:10:00,-0.000582,0.002832,-0.000502,0.000739,0.000261,0.001891,0.000775,-0.001172,0.000216,-0.000432,...,0.000360,-0.000105,-0.000159,-0.000362,0.000092,0.001131,0.001170,0.000202,0.000556,0.000475
10:15:00,-0.001997,0.001091,0.000111,-0.000192,0.000407,-0.001392,-0.000477,-0.001526,0.000198,-0.001821,...,0.001121,-0.000284,0.003272,-0.001107,-0.001012,-0.000174,0.001002,0.001815,-0.000168,0.000973
10:20:00,-0.000037,-0.000505,-0.000327,-0.000580,-0.000436,-0.000405,0.001263,0.000676,-0.002667,0.001033,...,0.000449,0.000335,0.000853,0.000981,-0.000057,-0.000096,0.000832,0.001951,0.001060,-0.001004

In [3]:
param_grid_0 = [
    {'kernel': ['gaussian', 'epanechnikov'],
        'bandwidth': ['silverman', 'scott', 'cv'],
        'adaptive': [True, False]}, 
    {'kernel': ['t_student'], 
        'df': range(2,6),
        'bandwidth': ['silverman', 'scott', 'cv'],
        'adaptive': [True, False]}]

param_grid = list(ParameterGrid(param_grid_0))

In [ ]:
params_dict = {}
records = []
for params in param_grid:
    print(params)
    df_support, df_densities = df_to_densities(df, params, verbose=False)
    try:
        cv_measures = cv(df_densities, df_support, initial_window=100)
    except Exception:
        continue
    for m in cv_measures:
        record = {
            # density
            "density_model": "f_hat",
            
            # parameters
            "kernel": params["kernel"],
            "bandwidth": params["bandwidth"],
            "adaptive": params["adaptive"],

            # CV info
            "fold": m["fold"],
            "method": m["method"],

            # metrics
            "KLD": float(m["KLD"]),
            "JSD": float(m["JSD"]),
            "L_1": float(m["L_1"]),
            "L_2": float(m["L_2"]),
            "L_INFTY": float(m["L_INFTY"]),
        }

        records.append(record)
    # title = f"kernel: {params["kernel"]} | bandwidth: {params["bandwidth"]} | adaptive: {params["adaptive"]}"
    # params_dict[title] = cv_measures
    # params_dict[title]["density"] = "f_hat"

results_df_1 = pd.DataFrame(records)

{'adaptive': True, 'bandwidth': 'silverman', 'kernel': 'gaussian'}
cv 0/149

c:\Users\user\anaconda3\envs\densities4risk\Lib\site-packages\scipy\interpolate\_interpolate.py:497: RuntimeWarning: overflow encountered in divide
  slope = (y_hi - y_lo) / (x_hi - x_lo)[:, None]
c:\Users\user\anaconda3\envs\densities4risk\Lib\site-packages\scipy\interpolate\_interpolate.py:500: RuntimeWarning: invalid value encountered in multiply
  y_new = slope*(x_new - x_lo)[:, None] + y_lo

cv 1/149

c:\Users\user\anaconda3\envs\densities4risk\Lib\site-packages\scipy\interpolate\_interpolate.py:497: RuntimeWarning: overflow encountered in divide
  slope = (y_hi - y_lo) / (x_hi - x_lo)[:, None]
c:\Users\user\anaconda3\envs\densities4risk\Lib\site-packages\scipy\interpolate\_interpolate.py:500: RuntimeWarning: invalid value encountered in multiply
  y_new = slope*(x_new - x_lo)[:, None] + y_lo

cv 2/149

c:\Users\user\anaconda3\envs\densities4risk\Lib\site-packages\scipy\interpolate\_interpolate.py:497: RuntimeWarning: overflow encountered in divide
  slope = (y_hi - y_lo) / (x_hi - x_lo)[:, None]
c:\Users\user\anaconda3\envs\densities4risk\Lib\site-packages\scipy\interpolate\_interpolate.py:500: RuntimeWarning: invalid value encountered in multiply
  y_new = slope*(x_new - x_lo)[:, None] + y_lo

cv 3/149

c:\Users\user\anaconda3\envs\densities4risk\Lib\site-packages\scipy\interpolate\_interpolate.py:497: RuntimeWarning: overflow encountered in divide
  slope = (y_hi - y_lo) / (x_hi - x_lo)[:, None]
c:\Users\user\anaconda3\envs\densities4risk\Lib\site-packages\scipy\interpolate\_interpolate.py:500: RuntimeWarning: invalid value encountered in multiply
  y_new = slope*(x_new - x_lo)[:, None] + y_lo

cv 4/149

c:\Users\user\anaconda3\envs\densities4risk\Lib\site-packages\scipy\interpolate\_interpolate.py:497: RuntimeWarning: overflow encountered in divide
  slope = (y_hi - y_lo) / (x_hi - x_lo)[:, None]
c:\Users\user\anaconda3\envs\densities4risk\Lib\site-packages\scipy\interpolate\_interpolate.py:500: RuntimeWarning: invalid value encountered in multiply
  y_new = slope*(x_new - x_lo)[:, None] + y_lo

cv 5/149

c:\Users\user\anaconda3\envs\densities4risk\Lib\site-packages\scipy\interpolate\_interpolate.py:497: RuntimeWarning: overflow encountered in divide
  slope = (y_hi - y_lo) / (x_hi - x_lo)[:, None]
c:\Users\user\anaconda3\envs\densities4risk\Lib\site-packages\scipy\interpolate\_interpolate.py:500: RuntimeWarning: invalid value encountered in multiply
  y_new = slope*(x_new - x_lo)[:, None] + y_lo

cv 6/149

c:\Users\user\anaconda3\envs\densities4risk\Lib\site-packages\scipy\interpolate\_interpolate.py:497: RuntimeWarning: overflow encountered in divide
  slope = (y_hi - y_lo) / (x_hi - x_lo)[:, None]
c:\Users\user\anaconda3\envs\densities4risk\Lib\site-packages\scipy\interpolate\_interpolate.py:500: RuntimeWarning: invalid value encountered in multiply
  y_new = slope*(x_new - x_lo)[:, None] + y_lo

cv 7/149

c:\Users\user\anaconda3\envs\densities4risk\Lib\site-packages\scipy\interpolate\_interpolate.py:497: RuntimeWarning: overflow encountered in divide
  slope = (y_hi - y_lo) / (x_hi - x_lo)[:, None]
c:\Users\user\anaconda3\envs\densities4risk\Lib\site-packages\scipy\interpolate\_interpolate.py:500: RuntimeWarning: invalid value encountered in multiply
  y_new = slope*(x_new - x_lo)[:, None] + y_lo

cv 8/149

c:\Users\user\anaconda3\envs\densities4risk\Lib\site-packages\scipy\interpolate\_interpolate.py:497: RuntimeWarning: overflow encountered in divide
  slope = (y_hi - y_lo) / (x_hi - x_lo)[:, None]
c:\Users\user\anaconda3\envs\densities4risk\Lib\site-packages\scipy\interpolate\_interpolate.py:500: RuntimeWarning: invalid value encountered in multiply
  y_new = slope*(x_new - x_lo)[:, None] + y_lo

cv 9/149

c:\Users\user\anaconda3\envs\densities4risk\Lib\site-packages\scipy\interpolate\_interpolate.py:497: RuntimeWarning: overflow encountered in divide
  slope = (y_hi - y_lo) / (x_hi - x_lo)[:, None]
c:\Users\user\anaconda3\envs\densities4risk\Lib\site-packages\scipy\interpolate\_interpolate.py:500: RuntimeWarning: invalid value encountered in multiply
  y_new = slope*(x_new - x_lo)[:, None] + y_lo

cv 10/149

c:\Users\user\anaconda3\envs\densities4risk\Lib\site-packages\scipy\interpolate\_interpolate.py:497: RuntimeWarning: overflow encountered in divide
  slope = (y_hi - y_lo) / (x_hi - x_lo)[:, None]
c:\Users\user\anaconda3\envs\densities4risk\Lib\site-packages\scipy\interpolate\_interpolate.py:500: RuntimeWarning: invalid value encountered in multiply
  y_new = slope*(x_new - x_lo)[:, None] + y_lo

cv 11/149

c:\Users\user\anaconda3\envs\densities4risk\Lib\site-packages\scipy\interpolate\_interpolate.py:497: RuntimeWarning: overflow encountered in divide
  slope = (y_hi - y_lo) / (x_hi - x_lo)[:, None]
c:\Users\user\anaconda3\envs\densities4risk\Lib\site-packages\scipy\interpolate\_interpolate.py:500: RuntimeWarning: invalid value encountered in multiply
  y_new = slope*(x_new - x_lo)[:, None] + y_lo

cv 12/149

c:\Users\user\anaconda3\envs\densities4risk\Lib\site-packages\scipy\interpolate\_interpolate.py:497: RuntimeWarning: overflow encountered in divide
  slope = (y_hi - y_lo) / (x_hi - x_lo)[:, None]
c:\Users\user\anaconda3\envs\densities4risk\Lib\site-packages\scipy\interpolate\_interpolate.py:500: RuntimeWarning: invalid value encountered in multiply
  y_new = slope*(x_new - x_lo)[:, None] + y_lo

cv 13/149

c:\Users\user\anaconda3\envs\densities4risk\Lib\site-packages\scipy\interpolate\_interpolate.py:497: RuntimeWarning: overflow encountered in divide
  slope = (y_hi - y_lo) / (x_hi - x_lo)[:, None]
c:\Users\user\anaconda3\envs\densities4risk\Lib\site-packages\scipy\interpolate\_interpolate.py:500: RuntimeWarning: invalid value encountered in multiply
  y_new = slope*(x_new - x_lo)[:, None] + y_lo

cv 14/149

c:\Users\user\anaconda3\envs\densities4risk\Lib\site-packages\scipy\interpolate\_interpolate.py:497: RuntimeWarning: overflow encountered in divide
  slope = (y_hi - y_lo) / (x_hi - x_lo)[:, None]
c:\Users\user\anaconda3\envs\densities4risk\Lib\site-packages\scipy\interpolate\_interpolate.py:500: RuntimeWarning: invalid value encountered in multiply
  y_new = slope*(x_new - x_lo)[:, None] + y_lo

cv 15/149

c:\Users\user\anaconda3\envs\densities4risk\Lib\site-packages\scipy\interpolate\_interpolate.py:497: RuntimeWarning: overflow encountered in divide
  slope = (y_hi - y_lo) / (x_hi - x_lo)[:, None]
c:\Users\user\anaconda3\envs\densities4risk\Lib\site-packages\scipy\interpolate\_interpolate.py:500: RuntimeWarning: invalid value encountered in multiply
  y_new = slope*(x_new - x_lo)[:, None] + y_lo

cv 16/149

c:\Users\user\anaconda3\envs\densities4risk\Lib\site-packages\scipy\interpolate\_interpolate.py:497: RuntimeWarning: overflow encountered in divide
  slope = (y_hi - y_lo) / (x_hi - x_lo)[:, None]
c:\Users\user\anaconda3\envs\densities4risk\Lib\site-packages\scipy\interpolate\_interpolate.py:500: RuntimeWarning: invalid value encountered in multiply
  y_new = slope*(x_new - x_lo)[:, None] + y_lo

cv 17/149

c:\Users\user\anaconda3\envs\densities4risk\Lib\site-packages\scipy\interpolate\_interpolate.py:497: RuntimeWarning: overflow encountered in divide
  slope = (y_hi - y_lo) / (x_hi - x_lo)[:, None]
c:\Users\user\anaconda3\envs\densities4risk\Lib\site-packages\scipy\interpolate\_interpolate.py:500: RuntimeWarning: invalid value encountered in multiply
  y_new = slope*(x_new - x_lo)[:, None] + y_lo

In [ ]:
records_norm = []
for params in param_grid:
    print(params)
    df_support, df_densities = df_to_densities(df, params, verbose=False)
    df_density_norm = weigh_norm_densities(df_densities, df_support.iloc[:,0])

    try:
        cv_measures = cv(df_density_norm, df_support, initial_window=100)
    except Exception:
        print(f"\t [ERROR] Problem for {params}. Continuing...")
        continue
    for m in cv_measures:
        record = {
            # density
            "density_model": "f_star",
            
            # parameters
            "kernel": params["kernel"],
            "bandwidth": params["bandwidth"],
            "adaptive": params["adaptive"],

            # CV info
            "fold": m["fold"],
            "method": m["method"],

            # metrics
            "KLD": float(m["KLD"]),
            "JSD": float(m["JSD"]),
            "L_1": float(m["L_1"]),
            "L_2": float(m["L_2"]),
            "L_INFTY": float(m["L_INFTY"]),
        }

        records.append(record)

results_df_2 = pd.DataFrame(records_norm)

{'adaptive': True, 'bandwidth': 'silverman', 'kernel': 'gaussian'}
cv 0/2

c:\Users\user\anaconda3\envs\densities4risk\Lib\site-packages\scipy\interpolate\_interpolate.py:497: RuntimeWarning: overflow encountered in divide
  slope = (y_hi - y_lo) / (x_hi - x_lo)[:, None]
c:\Users\user\anaconda3\envs\densities4risk\Lib\site-packages\scipy\interpolate\_interpolate.py:500: RuntimeWarning: invalid value encountered in multiply
  y_new = slope*(x_new - x_lo)[:, None] + y_lo

cv 1/2

c:\Users\user\anaconda3\envs\densities4risk\Lib\site-packages\scipy\interpolate\_interpolate.py:497: RuntimeWarning: overflow encountered in divide
  slope = (y_hi - y_lo) / (x_hi - x_lo)[:, None]
c:\Users\user\anaconda3\envs\densities4risk\Lib\site-packages\scipy\interpolate\_interpolate.py:500: RuntimeWarning: invalid value encountered in multiply
  y_new = slope*(x_new - x_lo)[:, None] + y_lo

{'adaptive': True, 'bandwidth': 'silverman', 'kernel': 'epanechnikov'}
cv 0/2
	 [ERROR] Problem for {'adaptive': True, 'bandwidth': 'silverman', 'kernel': 'epanechnikov'}. Continuing...
{'adaptive': True, 'bandwidth': 'scott', 'kernel': 'gaussian'}

c:\Users\user\Projetos\densities4risk\notebooks\..\src\transformations.py:213: RuntimeWarning: divide by zero encountered in log
  lqd_temp = -np.log(dens[keep])
c:\Users\user\anaconda3\envs\densities4risk\Lib\site-packages\scipy\interpolate\_interpolate.py:500: RuntimeWarning: invalid value encountered in add
  y_new = slope*(x_new - x_lo)[:, None] + y_lo
c:\Users\user\anaconda3\envs\densities4risk\Lib\site-packages\scipy\interpolate\_interpolate.py:500: RuntimeWarning: invalid value encountered in multiply
  y_new = slope*(x_new - x_lo)[:, None] + y_lo
c:\Users\user\Projetos\densities4risk\notebooks\..\src\dynamicFPC.py:184: RuntimeWarning: invalid value encountered in subtract
  Ydev = Y - Ybar

cv 0/2
cv 1/2
{'adaptive': True, 'bandwidth': 'scott', 'kernel': 'epanechnikov'}
cv 0/2

c:\Users\user\Projetos\densities4risk\notebooks\..\src\transformations.py:213: RuntimeWarning: divide by zero encountered in log
  lqd_temp = -np.log(dens[keep])

cv 1/2

c:\Users\user\Projetos\densities4risk\notebooks\..\src\transformations.py:213: RuntimeWarning: divide by zero encountered in log
  lqd_temp = -np.log(dens[keep])

{'adaptive': True, 'bandwidth': 'cv', 'kernel': 'gaussian'}

KeyboardInterrupt:

In [ ]:
results_df_1 = pd.DataFrame(records)
results_df_2 = pd.DataFrame(records_norm)
results_df = pd.concat([results_df_1, results_df_2], axis=0, ignore_index=True)

In [ ]:
results_df.to_excel("../data/processed/cv_density_estimation.xlsx", index=False)

,density_model,kernel,bandwidth,adaptive,fold,method,KLD,JSD,L_1,L_2,L_INFTY
0,f_hat,gaussian,silverman,True,0,KLE,0.655501,0.064915,0.602639,0.175067,0.097666
1,f_hat,gaussian,silverman,True,1,KLE,0.193302,0.010484,0.205594,0.063521,0.041949
2,f_hat,gaussian,scott,True,0,KLE,0.648989,0.070260,0.630713,0.180974,0.105293
3,f_hat,gaussian,scott,True,1,KLE,0.120902,0.004323,0.128030,0.036736,0.021941
4,f_star,gaussian,silverman,True,0,KLE,0.321927,0.035586,0.411393,0.139226,0.082964
5,f_star,gaussian,silverman,True,1,KLE,0.153567,0.009215,0.217022,0.082363,0.051879
6,f_star,gaussian,scott,True,0,KLE,0.329293,0.036082,0.417181,0.141246,0.088106
7,f_star,gaussian,scott,True,1,KLE,0.143495,0.005359,0.153702,0.051931,0.029536
8,f_star,epanechnikov,scott,True,0,KLE,0.364247,0.039041,0.435058,0.144051,0.082024
9,f_star,epanechnikov,scott,True,1,KLE,0.195157,0.010664,0.226170,0.086490,0.053181

In [ ]:
metrics = ["KLD", "JSD", "L_1", "L_2", "L_INFTY"]

mean_df = (
    results_df
    .groupby(["density_model", "kernel", "bandwidth", "adaptive"])[metrics]
    .mean()
    .reset_index()
)
for m in metrics:
    best_value = mean_df[m].min()
    mean_df[f"win_{m}"] = mean_df[m] == best_value

win_cols = [f"win_{m}" for m in metrics]

mean_df["n_wins"] = mean_df[win_cols].sum(axis=1)

best_overall = mean_df.sort_values("n_wins", ascending=False).iloc[0]
best_overall

density_model      f_star
kernel           gaussian
bandwidth           scott
adaptive             True
KLD              0.236394
JSD              0.020721
L_1              0.285442
L_2              0.096589
L_INFTY          0.058821
win_KLD              True
win_JSD              True
win_L_1              True
win_L_2              True
win_L_INFTY          True
n_wins                  5
Name: 3, dtype: object